# Generated by Django 2.2.19 on 2021-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseinfo',
            name='brand',
            field=models.FileField(default='static/img/HouseImg/brand/defaultBrand.png',
                                   upload_to='static/img/HouseImg/brand', verbose_name='公寓商标'),
        ),
        migrations.AddField(
            model_name='houseinfo',
            name='houseSlogan',
            field=models.CharField(default='给你家的感觉', max_length=16, verbose_name='公寓标语'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract',
            field=models.TextField(default='合同内容', verbose_name='合同内容'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseDesc',
            field=models.CharField(default='默认公寓简介', max_length=256, verbose_name='公寓简介'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseImg',
            field=models.FileField(default='static/img/HouseImg/defaultHouse.png', upload_to='static/img/HouseImg',
                                   verbose_name='公寓照片'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseName',
            field=models.CharField(default='默认公寓名', max_length=8, verbose_name='公寓名称'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='location',
            field=models.CharField(default='中国', max_length=32, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomDesc',
            field=models.CharField(default='默认房间描述', max_length=255, verbose_name='房间描述'),
        ),
        migrations.AlterField(
            model_name='room',
            name='roomImg',
            field=models.FileField(default='static/img/RoomImg/defaultRoom', upload_to='static/img/RoomImg',
                                   verbose_name='房间照片'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='TypeDesc',
            field=models.CharField(default='默认房间描述', max_length=255, verbose_name='房间描述'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='area',
            field=models.FloatField(default=0, verbose_name='大致面积'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='eDeposit',
            field=models.FloatField(default=0, verbose_name='预估押金'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='edayRent',
            field=models.FloatField(default=0, verbose_name='预估租金/天'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='emonRent',
            field=models.FloatField(default=0, verbose_name='预估租金/月'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='typeImg',
            field=models.FileField(default='static/img/TypeImg/defaultType', upload_to='static/img/TypeImg',
                                   verbose_name='房型示例'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='typeName',
            field=models.CharField(default='默认房型', max_length=16, verbose_name='房型名称'),
        ),
    ]
