# Generated by Django 2.2.19 on 2021-03-28 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Manager', '0002_auto_20210327_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': '合同', 'verbose_name_plural': '合同'},
        ),
        migrations.AlterModelOptions(
            name='houseinfo',
            options={'verbose_name': '公寓信息', 'verbose_name_plural': '公寓信息'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '房间信息', 'verbose_name_plural': '房间信息'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': '房型信息', 'verbose_name_plural': '房型信息'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='userdetail',
            options={'verbose_name': '用户个人信息', 'verbose_name_plural': '用户个人信息'},
        ),
        migrations.AddField(
            model_name='userdetail',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '隐藏'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manager.Room', verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL,
                                    verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='houseSlogan',
            field=models.CharField(default='默认标语', max_length=16, verbose_name='公寓标语'),
        ),
        migrations.AlterField(
            model_name='houseinfo',
            name='location',
            field=models.CharField(default='默认地址', max_length=32, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payState',
            field=models.BooleanField(choices=[(True, '已支付'), (False, '未支付')], default=False, verbose_name='支付情况'),
        ),
        migrations.AlterField(
            model_name='order',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manager.Room', verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL,
                                    verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '闲置中'), (1, '预定中'), (2, '使用中')], default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Manager.RoomType',
                                    verbose_name='房型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.UserDetail',
                                       verbose_name='个人信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Manager.Room',
                                    verbose_name='房间号'),
        ),
    ]
