# Generated by Django 2.2.19 on 2021-03-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Manager', '0003_auto_20210328_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDesc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='订单描述'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='Manager.RoomType', verbose_name='房型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='Manager.UserDetail', verbose_name='个人信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='Manager.Room', verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='cardCopy',
            field=models.FileField(blank=True, null=True, upload_to='id_card', verbose_name='身份证复印件'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='idCard',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='realname',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='真实姓名'),
        ),
    ]
