# Generated by Django 2.2.19 on 2021-03-30 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Manager', '0005_auto_20210328_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                       to='Manager.UserDetail', verbose_name='个人信息'),
        ),
    ]
