# Generated by Django 2.2.19 on 2021-04-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Manager', '0007_auto_20210330_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payState',
            field=models.BooleanField(choices=[(True, '已支付'), (False, '未支付')], default=False, verbose_name='支付情况'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='Contracts', verbose_name='实体合同'),
        ),
    ]
